// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaYJnYtHnxikq3eVg8-m2mnIdXunvnFcE',
    appId: '1:825852441532:web:9923439b79e50fe6c471b9',
    messagingSenderId: '825852441532',
    projectId: 'app-vinh-danh',
    authDomain: 'app-vinh-danh.firebaseapp.com',
    storageBucket: 'app-vinh-danh.appspot.com',
    measurementId: 'G-FRF64Z91L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJ9tBi-Xa7lyReZKN0KmlAc91JGaKeck',
    appId: '1:825852441532:android:d058b6f05554b5f3c471b9',
    messagingSenderId: '825852441532',
    projectId: 'app-vinh-danh',
    storageBucket: 'app-vinh-danh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOh-uU6C7tuC_5b0Ez7H8R9u86c1K1xQ4',
    appId: '1:825852441532:ios:0784f132d84dcbaec471b9',
    messagingSenderId: '825852441532',
    projectId: 'app-vinh-danh',
    storageBucket: 'app-vinh-danh.appspot.com',
    iosClientId: '825852441532-ag76ddp7h3u0dk8mor2vrb08cml68jf1.apps.googleusercontent.com',
    iosBundleId: 'vn.doitsolutions.honorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOh-uU6C7tuC_5b0Ez7H8R9u86c1K1xQ4',
    appId: '1:825852441532:ios:3c7b624002d125f4c471b9',
    messagingSenderId: '825852441532',
    projectId: 'app-vinh-danh',
    storageBucket: 'app-vinh-danh.appspot.com',
    iosClientId: '825852441532-si4vf3tqhgab3hnai1gtt0ioi8665opi.apps.googleusercontent.com',
    iosBundleId: 'com.example.honorsApp',
  );
}
